{% set name = "cpppo" %}
{% set version = "5.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cpppo-{{ version }}.tar.gz
  sha256: 0e23b97ba6ddc520c67a65a033b3962f6aa789981a823981fe9afd606e6b62a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - enip_server = cpppo.server.enip.main:main
    - enip_client = cpppo.server.enip.client:main
    - enip_get_attribute = cpppo.server.enip.get_attribute:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - greenery >=2.0,<3.0

test:
  imports:
    - cpppo
    - cpppo.server
    - cpppo.server.enip
  commands:
    - enip_server --help
    - enip_client --help
    - enip_get_attribute --help

about:
  home: https://github.com/pjkundert/cpppo
  summary: Cpppo is a Communication Protocol Python Parser and Originator
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - COPYING

extra:
  recipe-maintainers:
    - beenje
