{% set name = "cpppo" %}
{% set version = "5.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cpppo-{{ version }}.tar.gz
  sha256: 50a3c34f2624d11c5f10f66912c61971334ee50d1452637e5fdf7b13a9cc2536

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - enip_server = cpppo.server.enip.main:main
    - enip_client = cpppo.server.enip.client:main
    - enip_get_attribute = cpppo.server.enip.get_attribute:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - greenery >=2.0,<3.0

test:
  imports:
    - cpppo
    - cpppo.server
    - cpppo.server.enip
  commands:
    - pip check
    - enip_server --help
    - enip_client --help
    - enip_get_attribute --help
  requires:
    - pip

about:
  home: https://github.com/pjkundert/cpppo
  summary: Cpppo is a Communication Protocol Python Parser and Originator
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - COPYING

extra:
  recipe-maintainers:
    - beenje
